version: '3.1'

services:
  postgresql:
    container_name: product-db
    image: 'bitnami/postgresql:13-debian-12'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=user
      - POSTGRESQL_DATABASE=product-db
    ports:
      - '5433:5432'
    volumes:
      - 'product_db_data:/bitnami/postgresql'

  product-api:
    build: './product-api'
    container_name: product-api
    depends_on:
      - product-db
      - sales_rabbit
    networks:
      - sales-network
    environment:
      - PORT=8081
      - API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
      - DB_HOST=product-db
      - DB_NAME=product-db
      - DB_USER=admin
      - DB_PASSWORD=123456
      - DB_PORT=5432
      - RABBIT_MQ_HOST=sales_rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - SALES_HOST=sales-api
      - SALES_PORT=8082
    ports:
      - 8081:8081

volumes:
   product_db_data:
    driver: local
