server:
  port: 8081

spring:
  application:
    name: product-api

  datasource:
    url: jdbc:postgresql://localhost:5433/product-db
    username: user
    password: user
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
